[build]
publish = "build"
command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; base-uri 'none'; child-src 'self' app.netlify.com; form-action 'none'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; object-src 'none'; script-src 'self' app.netlify.com netlify-cdp-loader.netlify.app 'unsafe-eval'; style-src 'self' fonts.googleapis.com 'unsafe-inline'; connect-src 'self'; prefetch-src 'self';"
    